### PR TITLE
feat: adding the ability to set the `isOutput` to true from within plugin

### PR DESCRIPTION
**Pull request by britztopher**
# Overview
Looking to get the ability to use the `isOutput` flag for later using in other stages that depend on the version

@lluchmk 
Let me know if you want me to update the section in the readme to include an example of using the value in other stages

### CODE REVIEW

**Comment by britztopher** [comment]
@lluchmk i dont see your comment anywhere

**Comment by lluchmk** [comment]
Can you see it [here](https://github.com/lluchmk/semantic-release-ado/pull/24/files/fbfe337546906a9c1c817e102c2ddf608e742a4d)? It's on the README, about the text.

**Comment by lluchmk** [comment]
I can see it even in this page hahahah
Updated the comment to mention you on it, if you can't see it I'll go ahead and merge it and later update the text.

**Review by lluchmk — COMMENTED** [review]
Small change to documentation.

**Comment by lluchmk** [comment]
> i think you might need to make sure you finished your review and comment isnt in pending status. You can just tell me within here if you want and i can address it

That was it, I feel so dumb now 🤦‍♂️ 

Should be showing now, thanks!!

**Comment by britztopher** [comment]
@lluchmk i updated PR to include an updated example on how to use in another job and added documentation on how to use it in another stage

**Comment by lluchmk** [comment]
That's awesome!!

Thank you very much for the PR and for the practice with dealing with it hahaha

**Pull request merged**
